name: SonarQube Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.8.2'

      - name: Add SonarQube Helm repo
        run: |
          helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube
          helm repo update

      - name: Create charts directory
        run: mkdir -p ./charts

      - name: Download SonarQube Helm chart
        run: |
          helm pull sonarqube/sonarqube --version 10.0.0 --destination ./charts

      - name: Log in to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker image
        run: |
          # Check if the chart file exists before unpacking
          if [ -f ./charts/sonarqube-10.0.0.tgz ]; then
            # Unpack the chart into the charts directory
            tar -xzf ./charts/sonarqube-10.0.0.tgz -C ./charts
          else
            echo "Error: Chart file sonarqube-10.0.0.tgz not found!"
            exit 1
          fi

          # Build the Docker image using the unpacked chart directory
          docker build -t ghcr.io/${{ github.repository_owner }}/sonarqube:latest ./charts/sonarqube

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/sonarqube:latest
