name: Download and Push SonarQube Helm Chart (Custom)

on:
  push:
    branches:
      - main

jobs:
  download_and_push:
    runs-on: ubuntu-latest  # Or use a runner image with Helm pre-installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Helm if not already available (Option 2)
      - name: Install Helm (if needed)  # Uncomment if using Option 2
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/v3.10.3/scripts/get-helm.sh
          chmod +x get_helm.sh
          ./get_helm.sh

      - name: Login to GitHub Container Registry
        uses: docker/login@v2
        with:
          username: ${{ secrets.GCR_USERNAME }}
          password: ${{ secrets.GCR_ACCESS_TOKEN }}
          registry: ghcr.io

      - name: Build the Helm chart (replace 'charts/sonar' with your path)
        run: helm package charts/sonar

      - name: Tag the chart with GHCR image
        run: docker tag sonar-*.tgz ghcr.io/clddevsecops/sonar-chart:latest

      - name: Push the chart to GHCR
        run: docker push ghcr.io/clddevsecops/sonar-chart:latest
