name: SonarQube Deployment

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: '3.8.0'

      - name: Initialize Helm
        run: |
          echo "Initializing Helm..."
          helm init --client-only || echo "Helm already initialized"

      - name: Create Helm repositories directory
        run: |
          echo "Creating Helm repositories directory..."
          mkdir -p "$HOME/.helm/repository"

      - name: Add SonarQube Helm repository
        run: |
          echo "Adding SonarQube Helm repository..."
          helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube || echo "Repository already added"
        
      - name: Update Helm repositories
        run: |
          echo "Updating Helm repositories..."
          helm repo update || echo "Failed to update repositories, but continuing"

      - name: List Helm repositories
        run: helm repo list
