name: Build and Push SonarQube Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Initialize Helm
        run: |
          # Create Helm directory and repository file if it does not exist
          mkdir -p ~/.config/helm
          echo "[]" > ~/.config/helm/repositories.yaml || true

      - name: Add SonarQube Helm Repository
        run: |
          helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube || echo "Repository already added"

      - name: Update Helm Repository
        run: |
          helm repo update || echo "Failed to update repos, but continuing"

      - name: Pull SonarQube Helm Chart
        run: |
          helm pull sonarqube/sonarqube --version 10.0.0 --destination ./charts || echo "Failed to pull the chart"

      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u clddevsecops --password-stdin

      - name: Check if the chart file exists
        run: |
          if [ -f ./charts/sonarqube-10.0.0.tgz ]; then
            echo "Chart file exists."
          else
            echo "Error: Chart file sonarqube-10.0.0.tgz not found!"
            exit 1
          fi

      - name: Unpack the Chart
        run: |
          if [ -f ./charts/sonarqube-10.0.0.tgz ]; then
            tar -xzf ./charts/sonarqube-10.0.0.tgz -C ./charts
          else
            echo "Error: Chart file sonarqube-10.0.0.tgz not found!"
            exit 1
          fi

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/clddevsecops/sonarqube:latest ./charts/sonarqube

      - name: Push Docker Image
        run: |
          docker push ghcr.io/clddevsecops/sonarqube:latest
