name: Download and Push SonarQube Helm Chart

on:
  push:
    branches:
      - main

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Add SonarSource Helm repo
        run: |
          helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube
          helm repo update

      - name: Download SonarQube Helm chart
        run: helm pull sonarqube/sonarqube --untar

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and Push Helm chart to GHCR
        run: |
          docker build -t ghcr.io/clddevsecops/sonarqube:latest ./sonarqube
          docker push ghcr.io/clddevsecops/sonarqube:latest
