name: Download and Push SonarQube Helm Chart (Custom)

on:
  push:
    branches:
      - main

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm (optional, adjust version if needed)
        uses: helm/charts@v3
        with:
          version: 'v3.10.3'

      - name: Login to GitHub Container Registry
        uses: docker/login@v2
        with:
          username: ${{ secrets.GCR_USERNAME }}  # Replace with your GHCR username
          password: ${{ secrets.GCR_ACCESS_TOKEN }}
          registry: ghcr.io

      - name: Build the Helm chart (replace 'charts/sonar' with your path)
        run: helm package charts/sonar

      - name: Tag the chart with GHCR image
        run: docker tag sonar-*.tgz ghcr.io/clddevsecops/sonar-chart:latest

      - name: Push the chart to GHCR
        run: docker push ghcr.io/clddevsecops/sonar-chart:latest
