name: SonarQube Helm Chart CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: '3.8.0'

      # Step 3: Add SonarQube Helm repository
      - name: Add SonarQube Helm repository
        run: |
          echo "Adding SonarQube Helm repository..."
          helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube
          echo "Updating Helm repositories..."
          helm repo update
          echo "Available repositories:"
          helm repo list

      # Step 4: Pull SonarQube Helm chart
      - name: Pull SonarQube Helm chart
        run: |
          echo "Pulling SonarQube Helm chart version 10.0.0..."
          helm pull sonarqube/sonarqube --version 10.0.0 --destination ./charts
          echo "Successfully pulled the chart."

      # Step 5: Login to GitHub Container Registry
      - name: Login to GHCR
        run: |
          echo "Logging in to GitHub Container Registry..."
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "clddevsecops" --password-stdin
          echo "Login succeeded."

      # Step 6: Validate chart file existence
      - name: Validate chart file existence
        run: |
          if [ -f ./charts/sonarqube-10.0.0.tgz ]; then
            echo "Chart file exists."
          else
            echo "Error: Chart file sonarqube-10.0.0.tgz not found!"
            exit 1
          fi

      # Step 7: Build Docker image
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t ghcr.io/clddevsecops/sonarqube:latest ./charts/sonarqube
          echo "Docker image built successfully."

      # Step 8: Push Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          echo "Pushing Docker image to GitHub Container Registry..."
          docker push ghcr.io/clddevsecops/sonarqube:latest
          echo "Docker image pushed successfully."
