name: Build and Push SonarQube Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Initialize Helm
        run: helm init --client-only || echo "Helm init not required"

      - name: Add SonarQube Helm Repository
        run: |
          helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube || echo "Repository already added"

      - name: Update Helm Repositories
        run: helm repo update

      - name: Pull SonarQube Chart
        run: helm pull sonarqube/sonarqube --version 10.0.0 --destination ./charts

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u clddevsecops --password-stdin

      - name: Check if the chart file exists before unpacking
        run: |
          if [ -f ./charts/sonarqube-10.0.0.tgz ]; then
            echo "Chart file found. Unpacking..."
            tar -xzf ./charts/sonarqube-10.0.0.tgz -C ./charts
          else
            echo "Error: Chart file sonarqube-10.0.0.tgz not found!"
            exit 1
          fi

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/clddevsecops/sonarqube:latest ./charts/sonarqube
          
      - name: Push the Docker image to GHCR
        run: |
          docker push ghcr.io/clddevsecops/sonarqube:latest
