name: SonarQube Helm Chart Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.8.0'  # Use a stable version of Helm

      - name: Add SonarQube Helm repo
        run: |
          helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube || echo "Repository already added"
          helm repo update || echo "Failed to update repos, but continuing"

      - name: Pull SonarQube Helm chart
        run: |
          helm pull sonarqube/sonarqube --version 10.0.0 --destination ./charts || echo "Failed to pull the chart"

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and push the Docker image
        run: |
          if [ -f ./charts/sonarqube-10.0.0.tgz ]; then
            docker build -t ghcr.io/clddevsecops/sonarqube:latest ./charts/sonarqube
            docker push ghcr.io/clddevsecops/sonarqube:latest
          else
            echo "Error: Chart file sonarqube-10.0.0.tgz not found!"
            exit 1
          fi

      - name: Cleanup
        run: |
          echo "Cleaning up temporary files"
          rm -rf ./charts/sonarqube-10.0.0.tgz

